# Generated by Django 3.1.2 on 2020-10-13 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy_count', models.IntegerField()),
                ('plasma', models.IntegerField()),
                ('skin_thickness', models.IntegerField()),
                ('blood_pressure', models.IntegerField()),
                ('insulin', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('pedigree', models.FloatField()),
                ('age', models.IntegerField()),
                ('prediction_result', models.BooleanField(blank=True, default=False)),
                ('type_one_result', models.BooleanField(blank=True, default=False)),
                ('type_two_result', models.BooleanField(blank=True, default=False)),
                ('gestational_result', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('middle_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('symptom', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='db_mellitus.symptom')),
            ],
        ),
    ]
